{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d9abf8bb-6247-4970-9e68-1a524d65d60c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.cluster import KMeans\n",
    "\n",
    "# ---------------------------\n",
    "# App Configuration\n",
    "# ---------------------------\n",
    "st.set_page_config(\n",
    "    page_title=\"Marketing Strategy Simulator\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "st.title(\"🎯 Marketing Strategy Simulator\")\n",
    "st.markdown(\n",
    "    \"\"\"\n",
    "    **Objective:** Identify target customers and simulate marketing ROI  \n",
    "    using income–spending segmentation (quadrant-based decision system).\n",
    "    \"\"\"\n",
    ")\n",
    "\n",
    "# ---------------------------\n",
    "# Load Data\n",
    "# ---------------------------\n",
    "@st.cache_data\n",
    "def load_data():\n",
    "    df = pd.read_csv(\"data/Mall_Customers.csv\")\n",
    "    return df\n",
    "\n",
    "df = load_data()\n",
    "\n",
    "# ---------------------------\n",
    "# Feature Engineering\n",
    "# ---------------------------\n",
    "X = df[[\"Annual Income (k$)\", \"Spending Score (1-100)\"]]\n",
    "scaler = StandardScaler()\n",
    "X_scaled = scaler.fit_transform(X)\n",
    "\n",
    "kmeans = KMeans(n_clusters=5, random_state=42)\n",
    "df[\"Cluster\"] = kmeans.fit_predict(X_scaled)\n",
    "\n",
    "income_median = df[\"Annual Income (k$)\"].median()\n",
    "spending_median = df[\"Spending Score (1-100)\"].median()\n",
    "\n",
    "def assign_quadrant(row):\n",
    "    if row[\"Annual Income (k$)\"] >= income_median and row[\"Spending Score (1-100)\"] >= spending_median:\n",
    "        return \"High Income – High Spending\"\n",
    "    elif row[\"Annual Income (k$)\"] >= income_median and row[\"Spending Score (1-100)\"] < spending_median:\n",
    "        return \"High Income – Low Spending\"\n",
    "    elif row[\"Annual Income (k$)\"] < income_median and row[\"Spending Score (1-100)\"] >= spending_median:\n",
    "        return \"Low Income – High Spending\"\n",
    "    else:\n",
    "        return \"Low Income – Low Spending\"\n",
    "\n",
    "df[\"Quadrant\"] = df.apply(assign_quadrant, axis=1)\n",
    "\n",
    "# ---------------------------\n",
    "# Sidebar Controls\n",
    "# ---------------------------\n",
    "st.sidebar.header(\"⚙️ Marketing Assumptions\")\n",
    "\n",
    "roi_high_high = st.sidebar.slider(\"ROI: High Income – High Spending\", 1.0, 3.0, 1.6, 0.1)\n",
    "roi_high_low = st.sidebar.slider(\"ROI: High Income – Low Spending\", 1.0, 3.0, 1.8, 0.1)\n",
    "roi_low_high = st.sidebar.slider(\"ROI: Low Income – High Spending\", 1.0, 3.0, 1.4, 0.1)\n",
    "roi_low_low = st.sidebar.slider(\"ROI: Low Income – Low Spending\", 0.5, 1.5, 0.8, 0.1)\n",
    "\n",
    "roi_map = {\n",
    "    \"High Income – High Spending\": roi_high_high,\n",
    "    \"High Income – Low Spending\": roi_high_low,\n",
    "    \"Low Income – High Spending\": roi_low_high,\n",
    "    \"Low Income – Low Spending\": roi_low_low\n",
    "}\n",
    "\n",
    "strategy_map = {\n",
    "    \"High Income – High Spending\": \"VIP Rewards & Loyalty\",\n",
    "    \"High Income – Low Spending\": \"Upselling & Personalised Offers\",\n",
    "    \"Low Income – High Spending\": \"Discounts & Flash Sales\",\n",
    "    \"Low Income – Low Spending\": \"No Promotion (Cost Control)\"\n",
    "}\n",
    "\n",
    "df[\"Expected_ROI\"] = df[\"Quadrant\"].map(roi_map)\n",
    "df[\"Strategy\"] = df[\"Quadrant\"].map(strategy_map)\n",
    "\n",
    "# ---------------------------\n",
    "# Main Layout\n",
    "# ---------------------------\n",
    "col1, col2 = st.columns(2)\n",
    "\n",
    "# ---- Quadrant Visualization\n",
    "with col1:\n",
    "    st.subheader(\"📊 Customer Segmentation Square\")\n",
    "\n",
    "    fig, ax = plt.subplots()\n",
    "    sns.scatterplot(\n",
    "        x=\"Annual Income (k$)\",\n",
    "        y=\"Spending Score (1-100)\",\n",
    "        hue=\"Quadrant\",\n",
    "        data=df,\n",
    "        ax=ax\n",
    "    )\n",
    "\n",
    "    ax.axvline(income_median, linestyle=\"--\", color=\"grey\")\n",
    "    ax.axhline(spending_median, linestyle=\"--\", color=\"grey\")\n",
    "    ax.set_title(\"Income vs Spending Quadrants\")\n",
    "\n",
    "    st.pyplot(fig)\n",
    "\n",
    "# ---- ROI Summary\n",
    "with col2:\n",
    "    st.subheader(\"💰 ROI Simulation Summary\")\n",
    "\n",
    "    roi_summary = df.groupby(\"Quadrant\").agg(\n",
    "        Customers=(\"CustomerID\", \"count\"),\n",
    "        Avg_ROI=(\"Expected_ROI\", \"mean\"),\n",
    "        Total_ROI=(\"Expected_ROI\", \"sum\")\n",
    "    ).sort_values(\"Total_ROI\", ascending=False)\n",
    "\n",
    "    st.dataframe(roi_summary, use_container_width=True)\n",
    "\n",
    "# ---------------------------\n",
    "# Targeting Decision\n",
    "# ---------------------------\n",
    "st.subheader(\"🎯 Targeting Recommendation\")\n",
    "\n",
    "df[\"Target_For_Promotion\"] = df[\"Quadrant\"] != \"Low Income – Low Spending\"\n",
    "\n",
    "target_summary = df.groupby(\"Target_For_Promotion\").agg(\n",
    "    Customers=(\"CustomerID\", \"count\"),\n",
    "    Avg_ROI=(\"Expected_ROI\", \"mean\")\n",
    ")\n",
    "\n",
    "st.dataframe(target_summary)\n",
    "\n",
    "st.markdown(\n",
    "    \"\"\"\n",
    "    **Decision Rule:**  \n",
    "    - Promote to all segments **except Low Income – Low Spending**  \n",
    "    - Focus budget where expected ROI is highest\n",
    "    \"\"\"\n",
    ")\n",
    "\n",
    "# ---------------------------\n",
    "# Customer-Level Explorer\n",
    "# ---------------------------\n",
    "st.subheader(\"👤 Customer-Level Strategy Explorer\")\n",
    "\n",
    "selected_customer = st.selectbox(\n",
    "    \"Select Customer ID\",\n",
    "    df[\"CustomerID\"].values\n",
    ")\n",
    "\n",
    "customer_row = df[df[\"CustomerID\"] == selected_customer]\n",
    "\n",
    "st.write(customer_row[[\n",
    "    \"CustomerID\",\n",
    "    \"Age\",\n",
    "    \"Annual Income (k$)\",\n",
    "    \"Spending Score (1-100)\",\n",
    "    \"Quadrant\",\n",
    "    \"Strategy\",\n",
    "    \"Expected_ROI\"\n",
    "]])\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
